### ISSUE TITLE
Unexpected token på rad 19 i friends.js enligt Heroku

### ISSUE THREAD

**Issue by jt222ii** [2dv612-team4/webchat#34]
https://github.com/2dv612-team4/webchat/blob/master/routes/friends.js#L19 

Heroku säger följande vid deploy:
2016-11-22T16:20:57.835806+00:00 app[web.1]: /app/routes/friends.js:19
2016-11-22T16:20:57.835810+00:00 app[web.1]:     const [ requesterUser, reciverUser ] = yield [
2016-11-22T16:20:57.835811+00:00 app[web.1]:           ^
2016-11-22T16:20:57.835811+00:00 app[web.1]: 
2016-11-22T16:20:57.835812+00:00 app[web.1]: SyntaxError: Unexpected token [
2016-11-22T16:20:57.835813+00:00 app[web.1]:     at exports.runInThisContext (vm.js:53:16)
2016-11-22T16:20:57.835814+00:00 app[web.1]:     at Module._compile (module.js:387:25)
2016-11-22T16:20:57.835815+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-11-22T16:20:57.835815+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-11-22T16:20:57.835816+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-11-22T16:20:57.835817+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-11-22T16:20:57.835818+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-11-22T16:20:57.835818+00:00 app[web.1]:     at Object.<anonymous> (/app/app.js:37:21)
2016-11-22T16:20:57.835819+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-11-22T16:20:57.835819+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-11-22T16:20:57.835820+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-11-22T16:20:57.835821+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-11-22T16:20:57.835821+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-11-22T16:20:57.835822+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-11-22T16:20:57.835823+00:00 app[web.1]:     at Object.<anonymous> (/app/bin/www:7:11)
2016-11-22T16:20:57.835827+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-11-22T16:20:57.850881+00:00 app[web.1]:

**Comment by MartinArvidsson** [comment]
Uptäcktes vid deploy från mastern

**Comment by dk222gs** [comment]
Fixed, updated node version on Heroku
